# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'demo-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo-ios
  pod 'THETAClient', '1.9.0'
  pod 'THETABleClient', '1.3.0'

end
