name: Test react native

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: test-rn
      run: |
        cd ./react-native
        yarn install
        yarn test --collectCoverage
    - name: Archive code coverage results
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: test-react-native-report
        path: react-native/coverage
